SELECT ANIMAL_ID, NAME
FROM 
    (SELECT I.ANIMAL_ID, I.NAME, O.DATETIME - I.DATETIME AS DURATION 
         FROM ANIMAL_INS I, ANIMAL_OUTS O
            WHERE I.ANIMAL_ID = O.ANIMAL_ID
                ORDER BY DURATION DESC )
    WHERE ROWNUM <= 2
